name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: "Reference: install"
        working-directory: "reference_gen"
        run: deno install

      - name: "Reference: generate types"
        working-directory: "reference_gen"
        run: deno task types

      - name: "Reference: generate docs"
        working-directory: "reference_gen"
        run: deno task doc

      - run: |
          deno task build
          cd _site && zip -r ../build-artifact.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.zip

  # deploy-to-server:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: build-artifact
  #         path: .

  #     - run: unzip -o build-artifact.zip -d extracted

  #     - uses: easingthemes/ssh-deploy@main
  #       with:
  #         REMOTE_HOST: ${{ secrets.SERVER_HOST }}
  #         REMOTE_PORT: ${{ secrets.SERVER_PORT }}
  #         REMOTE_USER: ${{ secrets.SERVER_USER }}
  #         SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
  #         SOURCE: 'extracted/'
  #         ARGS: '-azr --delete'
  #         TARGET: '${{ secrets.SERVER_PATH }}/${{ github.event.repository.name }}/'

  push-to-branch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_TOKEN }}

      - run: |
          git checkout --orphan site
          git rm -rf . >/dev/null

      - uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - run: |
          unzip -o build-artifact.zip -d .
          rm -f build-artifact.zip

      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "upload build artifact to site branch"
          git push origin site -f
